apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    user: user-k6
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      dbName: k6
      httpMode: GET
    secureJsonData:
      password: user-k6-pass
