{
 "title": "Evaluation-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "http-req scenario",
   "type": "timeseries",
   "description": "Scenario test",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "scenario::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "http-req duration",
   "type": "timeseries",
   "description": "Time by request ",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "http-req-duration",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "http-req-percentage",
   "type": "piechart",
   "description": "Virtual users by test",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "http-req-ok",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "status::tag", "operator": "=", "value": "200" }
     ]
    },
    {
     "alias": "http-req-bad",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "status::tag", "operator": "=", "value": "500" }
     ]
    }
   ]
  },
  {
   "title": "http-req vus",
   "type": "timeseries",
   "description": "Virtual users by test",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "http-req-vus",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}